// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/media.dart';
import 'api/monitor.dart';
import 'api/system.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<MediaSession?>
      dco_decode_StreamSink_opt_box_autoadd_media_session_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MediaSession dco_decode_box_autoadd_media_session(dynamic raw);

  @protected
  MonitorResolution dco_decode_box_autoadd_monitor_resolution(dynamic raw);

  @protected
  CoreStatus dco_decode_core_status(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MediaCapabilities dco_decode_media_capabilities(dynamic raw);

  @protected
  MediaPlaybackState dco_decode_media_playback_state(dynamic raw);

  @protected
  MediaSession dco_decode_media_session(dynamic raw);

  @protected
  MonitorMode dco_decode_monitor_mode(dynamic raw);

  @protected
  MonitorResolution dco_decode_monitor_resolution(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  MediaSession? dco_decode_opt_box_autoadd_media_session(dynamic raw);

  @protected
  MonitorResolution? dco_decode_opt_box_autoadd_monitor_resolution(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<MediaSession?>
      sse_decode_StreamSink_opt_box_autoadd_media_session_Sse(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MediaSession sse_decode_box_autoadd_media_session(
      SseDeserializer deserializer);

  @protected
  MonitorResolution sse_decode_box_autoadd_monitor_resolution(
      SseDeserializer deserializer);

  @protected
  CoreStatus sse_decode_core_status(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MediaCapabilities sse_decode_media_capabilities(SseDeserializer deserializer);

  @protected
  MediaPlaybackState sse_decode_media_playback_state(
      SseDeserializer deserializer);

  @protected
  MediaSession sse_decode_media_session(SseDeserializer deserializer);

  @protected
  MonitorMode sse_decode_monitor_mode(SseDeserializer deserializer);

  @protected
  MonitorResolution sse_decode_monitor_resolution(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  MediaSession? sse_decode_opt_box_autoadd_media_session(
      SseDeserializer deserializer);

  @protected
  MonitorResolution? sse_decode_opt_box_autoadd_monitor_resolution(
      SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_opt_box_autoadd_media_session_Sse(
      RustStreamSink<MediaSession?> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_media_session(
      MediaSession self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_monitor_resolution(
      MonitorResolution self, SseSerializer serializer);

  @protected
  void sse_encode_core_status(CoreStatus self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_media_capabilities(
      MediaCapabilities self, SseSerializer serializer);

  @protected
  void sse_encode_media_playback_state(
      MediaPlaybackState self, SseSerializer serializer);

  @protected
  void sse_encode_media_session(MediaSession self, SseSerializer serializer);

  @protected
  void sse_encode_monitor_mode(MonitorMode self, SseSerializer serializer);

  @protected
  void sse_encode_monitor_resolution(
      MonitorResolution self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_media_session(
      MediaSession? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_monitor_resolution(
      MonitorResolution? self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
