// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/clipboard.dart';
import 'api/fullscreen.dart';
import 'api/media.dart';
import 'api/monitor.dart';
import 'api/system.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSystemInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -527956355;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'islanddesk_bridge',
    ioDirectory: '../rust/crates/bridge/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  bool crateApiClipboardClipboardSecurityPlatformSupported();

  String crateApiClipboardDecryptClipboardText(
      {required String itemId,
      required List<int> nonce,
      required List<int> ciphertext});

  ClipboardEncryptedData crateApiClipboardEncryptClipboardText(
      {required String itemId, required String plaintext});

  bool crateApiFullscreenFullscreenPlatformSupported();

  CoreStatus crateApiSystemGetCoreStatus();

  Future<MediaSession?> crateApiMediaGetCurrentMediaSession();

  Future<void> crateApiSystemInitApp();

  ClipboardSecurityStatus crateApiClipboardInitializeClipboardSecurity();

  Future<bool> crateApiFullscreenIsForegroundFullscreen();

  Future<bool> crateApiMediaMediaNext();

  bool crateApiMediaMediaPlatformSupported();

  Future<bool> crateApiMediaMediaPlayPause();

  Future<bool> crateApiMediaMediaPrevious();

  Future<bool> crateApiMediaMediaSeek({required BigInt positionMs});

  MonitorResolution? crateApiMonitorResolveMonitor(
      {required MonitorMode mode,
      required List<String> displayIds,
      required String primaryId,
      String? activeId,
      String? fixedId});

  Stream<String?> crateApiClipboardWatchClipboardText();

  Stream<MediaSession?> crateApiMediaWatchMediaSessions();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  bool crateApiClipboardClipboardSecurityPlatformSupported() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiClipboardClipboardSecurityPlatformSupportedConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiClipboardClipboardSecurityPlatformSupportedConstMeta =>
          const TaskConstMeta(
            debugName: "clipboard_security_platform_supported",
            argNames: [],
          );

  @override
  String crateApiClipboardDecryptClipboardText(
      {required String itemId,
      required List<int> nonce,
      required List<int> ciphertext}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(itemId, serializer);
        sse_encode_list_prim_u_8_loose(nonce, serializer);
        sse_encode_list_prim_u_8_loose(ciphertext, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiClipboardDecryptClipboardTextConstMeta,
      argValues: [itemId, nonce, ciphertext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClipboardDecryptClipboardTextConstMeta =>
      const TaskConstMeta(
        debugName: "decrypt_clipboard_text",
        argNames: ["itemId", "nonce", "ciphertext"],
      );

  @override
  ClipboardEncryptedData crateApiClipboardEncryptClipboardText(
      {required String itemId, required String plaintext}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(itemId, serializer);
        sse_encode_String(plaintext, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_clipboard_encrypted_data,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiClipboardEncryptClipboardTextConstMeta,
      argValues: [itemId, plaintext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClipboardEncryptClipboardTextConstMeta =>
      const TaskConstMeta(
        debugName: "encrypt_clipboard_text",
        argNames: ["itemId", "plaintext"],
      );

  @override
  bool crateApiFullscreenFullscreenPlatformSupported() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFullscreenFullscreenPlatformSupportedConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFullscreenFullscreenPlatformSupportedConstMeta =>
      const TaskConstMeta(
        debugName: "fullscreen_platform_supported",
        argNames: [],
      );

  @override
  CoreStatus crateApiSystemGetCoreStatus() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_core_status,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSystemGetCoreStatusConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSystemGetCoreStatusConstMeta =>
      const TaskConstMeta(
        debugName: "get_core_status",
        argNames: [],
      );

  @override
  Future<MediaSession?> crateApiMediaGetCurrentMediaSession() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_media_session,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiMediaGetCurrentMediaSessionConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMediaGetCurrentMediaSessionConstMeta =>
      const TaskConstMeta(
        debugName: "get_current_media_session",
        argNames: [],
      );

  @override
  Future<void> crateApiSystemInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSystemInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSystemInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  ClipboardSecurityStatus crateApiClipboardInitializeClipboardSecurity() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_clipboard_security_status,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiClipboardInitializeClipboardSecurityConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClipboardInitializeClipboardSecurityConstMeta =>
      const TaskConstMeta(
        debugName: "initialize_clipboard_security",
        argNames: [],
      );

  @override
  Future<bool> crateApiFullscreenIsForegroundFullscreen() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiFullscreenIsForegroundFullscreenConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFullscreenIsForegroundFullscreenConstMeta =>
      const TaskConstMeta(
        debugName: "is_foreground_fullscreen",
        argNames: [],
      );

  @override
  Future<bool> crateApiMediaMediaNext() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiMediaMediaNextConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMediaMediaNextConstMeta => const TaskConstMeta(
        debugName: "media_next",
        argNames: [],
      );

  @override
  bool crateApiMediaMediaPlatformSupported() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMediaMediaPlatformSupportedConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMediaMediaPlatformSupportedConstMeta =>
      const TaskConstMeta(
        debugName: "media_platform_supported",
        argNames: [],
      );

  @override
  Future<bool> crateApiMediaMediaPlayPause() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiMediaMediaPlayPauseConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMediaMediaPlayPauseConstMeta =>
      const TaskConstMeta(
        debugName: "media_play_pause",
        argNames: [],
      );

  @override
  Future<bool> crateApiMediaMediaPrevious() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiMediaMediaPreviousConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMediaMediaPreviousConstMeta => const TaskConstMeta(
        debugName: "media_previous",
        argNames: [],
      );

  @override
  Future<bool> crateApiMediaMediaSeek({required BigInt positionMs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_64(positionMs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiMediaMediaSeekConstMeta,
      argValues: [positionMs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMediaMediaSeekConstMeta => const TaskConstMeta(
        debugName: "media_seek",
        argNames: ["positionMs"],
      );

  @override
  MonitorResolution? crateApiMonitorResolveMonitor(
      {required MonitorMode mode,
      required List<String> displayIds,
      required String primaryId,
      String? activeId,
      String? fixedId}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_monitor_mode(mode, serializer);
        sse_encode_list_String(displayIds, serializer);
        sse_encode_String(primaryId, serializer);
        sse_encode_opt_String(activeId, serializer);
        sse_encode_opt_String(fixedId, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_monitor_resolution,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMonitorResolveMonitorConstMeta,
      argValues: [mode, displayIds, primaryId, activeId, fixedId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMonitorResolveMonitorConstMeta =>
      const TaskConstMeta(
        debugName: "resolve_monitor",
        argNames: ["mode", "displayIds", "primaryId", "activeId", "fixedId"],
      );

  @override
  Stream<String?> crateApiClipboardWatchClipboardText() {
    final sink = RustStreamSink<String?>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_opt_String_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiClipboardWatchClipboardTextConstMeta,
      argValues: [sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiClipboardWatchClipboardTextConstMeta =>
      const TaskConstMeta(
        debugName: "watch_clipboard_text",
        argNames: ["sink"],
      );

  @override
  Stream<MediaSession?> crateApiMediaWatchMediaSessions() {
    final sink = RustStreamSink<MediaSession?>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_opt_box_autoadd_media_session_Sse(
            sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiMediaWatchMediaSessionsConstMeta,
      argValues: [sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMediaWatchMediaSessionsConstMeta =>
      const TaskConstMeta(
        debugName: "watch_media_sessions",
        argNames: ["sink"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<String?> dco_decode_StreamSink_opt_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<MediaSession?>
      dco_decode_StreamSink_opt_box_autoadd_media_session_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  MediaSession dco_decode_box_autoadd_media_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_media_session(raw);
  }

  @protected
  MonitorResolution dco_decode_box_autoadd_monitor_resolution(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_monitor_resolution(raw);
  }

  @protected
  ClipboardEncryptedData dco_decode_clipboard_encrypted_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ClipboardEncryptedData(
      nonce: dco_decode_list_prim_u_8_strict(arr[0]),
      ciphertext: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  ClipboardSecurityStatus dco_decode_clipboard_security_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ClipboardSecurityStatus(
      supported: dco_decode_bool(arr[0]),
      ready: dco_decode_bool(arr[1]),
      backend: dco_decode_String(arr[2]),
      errorCode: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  CoreStatus dco_decode_core_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CoreStatus(
      name: dco_decode_String(arr[0]),
      version: dco_decode_String(arr[1]),
      targetOs: dco_decode_String(arr[2]),
      targetArch: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MediaCapabilities dco_decode_media_capabilities(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MediaCapabilities(
      canPlay: dco_decode_bool(arr[0]),
      canPause: dco_decode_bool(arr[1]),
      canNext: dco_decode_bool(arr[2]),
      canPrevious: dco_decode_bool(arr[3]),
      canSeek: dco_decode_bool(arr[4]),
    );
  }

  @protected
  MediaPlaybackState dco_decode_media_playback_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MediaPlaybackState.values[raw as int];
  }

  @protected
  MediaSession dco_decode_media_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return MediaSession(
      sourceAppId: dco_decode_String(arr[0]),
      sourceAppName: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      artist: dco_decode_String(arr[3]),
      albumTitle: dco_decode_String(arr[4]),
      playbackState: dco_decode_media_playback_state(arr[5]),
      positionMs: dco_decode_u_64(arr[6]),
      durationMs: dco_decode_u_64(arr[7]),
      artwork: dco_decode_list_prim_u_8_strict(arr[8]),
      artworkContentType: dco_decode_String(arr[9]),
      capabilities: dco_decode_media_capabilities(arr[10]),
    );
  }

  @protected
  MonitorMode dco_decode_monitor_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MonitorMode.values[raw as int];
  }

  @protected
  MonitorResolution dco_decode_monitor_resolution(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MonitorResolution(
      displayId: dco_decode_String(arr[0]),
      usedFallback: dco_decode_bool(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  MediaSession? dco_decode_opt_box_autoadd_media_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_media_session(raw);
  }

  @protected
  MonitorResolution? dco_decode_opt_box_autoadd_monitor_resolution(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_monitor_resolution(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<String?> sse_decode_StreamSink_opt_String_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<MediaSession?>
      sse_decode_StreamSink_opt_box_autoadd_media_session_Sse(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  MediaSession sse_decode_box_autoadd_media_session(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_media_session(deserializer));
  }

  @protected
  MonitorResolution sse_decode_box_autoadd_monitor_resolution(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_monitor_resolution(deserializer));
  }

  @protected
  ClipboardEncryptedData sse_decode_clipboard_encrypted_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nonce = sse_decode_list_prim_u_8_strict(deserializer);
    var var_ciphertext = sse_decode_list_prim_u_8_strict(deserializer);
    return ClipboardEncryptedData(nonce: var_nonce, ciphertext: var_ciphertext);
  }

  @protected
  ClipboardSecurityStatus sse_decode_clipboard_security_status(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_supported = sse_decode_bool(deserializer);
    var var_ready = sse_decode_bool(deserializer);
    var var_backend = sse_decode_String(deserializer);
    var var_errorCode = sse_decode_opt_String(deserializer);
    return ClipboardSecurityStatus(
        supported: var_supported,
        ready: var_ready,
        backend: var_backend,
        errorCode: var_errorCode);
  }

  @protected
  CoreStatus sse_decode_core_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    var var_targetOs = sse_decode_String(deserializer);
    var var_targetArch = sse_decode_String(deserializer);
    return CoreStatus(
        name: var_name,
        version: var_version,
        targetOs: var_targetOs,
        targetArch: var_targetArch);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MediaCapabilities sse_decode_media_capabilities(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_canPlay = sse_decode_bool(deserializer);
    var var_canPause = sse_decode_bool(deserializer);
    var var_canNext = sse_decode_bool(deserializer);
    var var_canPrevious = sse_decode_bool(deserializer);
    var var_canSeek = sse_decode_bool(deserializer);
    return MediaCapabilities(
        canPlay: var_canPlay,
        canPause: var_canPause,
        canNext: var_canNext,
        canPrevious: var_canPrevious,
        canSeek: var_canSeek);
  }

  @protected
  MediaPlaybackState sse_decode_media_playback_state(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MediaPlaybackState.values[inner];
  }

  @protected
  MediaSession sse_decode_media_session(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourceAppId = sse_decode_String(deserializer);
    var var_sourceAppName = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_String(deserializer);
    var var_albumTitle = sse_decode_String(deserializer);
    var var_playbackState = sse_decode_media_playback_state(deserializer);
    var var_positionMs = sse_decode_u_64(deserializer);
    var var_durationMs = sse_decode_u_64(deserializer);
    var var_artwork = sse_decode_list_prim_u_8_strict(deserializer);
    var var_artworkContentType = sse_decode_String(deserializer);
    var var_capabilities = sse_decode_media_capabilities(deserializer);
    return MediaSession(
        sourceAppId: var_sourceAppId,
        sourceAppName: var_sourceAppName,
        title: var_title,
        artist: var_artist,
        albumTitle: var_albumTitle,
        playbackState: var_playbackState,
        positionMs: var_positionMs,
        durationMs: var_durationMs,
        artwork: var_artwork,
        artworkContentType: var_artworkContentType,
        capabilities: var_capabilities);
  }

  @protected
  MonitorMode sse_decode_monitor_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MonitorMode.values[inner];
  }

  @protected
  MonitorResolution sse_decode_monitor_resolution(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_displayId = sse_decode_String(deserializer);
    var var_usedFallback = sse_decode_bool(deserializer);
    return MonitorResolution(
        displayId: var_displayId, usedFallback: var_usedFallback);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MediaSession? sse_decode_opt_box_autoadd_media_session(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_media_session(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MonitorResolution? sse_decode_opt_box_autoadd_monitor_resolution(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_monitor_resolution(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_opt_String_Sse(
      RustStreamSink<String?> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_opt_box_autoadd_media_session_Sse(
      RustStreamSink<MediaSession?> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_media_session,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_media_session(
      MediaSession self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_media_session(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_monitor_resolution(
      MonitorResolution self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_monitor_resolution(self, serializer);
  }

  @protected
  void sse_encode_clipboard_encrypted_data(
      ClipboardEncryptedData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.nonce, serializer);
    sse_encode_list_prim_u_8_strict(self.ciphertext, serializer);
  }

  @protected
  void sse_encode_clipboard_security_status(
      ClipboardSecurityStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.supported, serializer);
    sse_encode_bool(self.ready, serializer);
    sse_encode_String(self.backend, serializer);
    sse_encode_opt_String(self.errorCode, serializer);
  }

  @protected
  void sse_encode_core_status(CoreStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.version, serializer);
    sse_encode_String(self.targetOs, serializer);
    sse_encode_String(self.targetArch, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_media_capabilities(
      MediaCapabilities self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.canPlay, serializer);
    sse_encode_bool(self.canPause, serializer);
    sse_encode_bool(self.canNext, serializer);
    sse_encode_bool(self.canPrevious, serializer);
    sse_encode_bool(self.canSeek, serializer);
  }

  @protected
  void sse_encode_media_playback_state(
      MediaPlaybackState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_media_session(MediaSession self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sourceAppId, serializer);
    sse_encode_String(self.sourceAppName, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.artist, serializer);
    sse_encode_String(self.albumTitle, serializer);
    sse_encode_media_playback_state(self.playbackState, serializer);
    sse_encode_u_64(self.positionMs, serializer);
    sse_encode_u_64(self.durationMs, serializer);
    sse_encode_list_prim_u_8_strict(self.artwork, serializer);
    sse_encode_String(self.artworkContentType, serializer);
    sse_encode_media_capabilities(self.capabilities, serializer);
  }

  @protected
  void sse_encode_monitor_mode(MonitorMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_monitor_resolution(
      MonitorResolution self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.displayId, serializer);
    sse_encode_bool(self.usedFallback, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_media_session(
      MediaSession? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_media_session(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_monitor_resolution(
      MonitorResolution? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_monitor_resolution(self, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
