// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `initialize`

bool clipboardSecurityPlatformSupported() =>
    RustLib.instance.api.crateApiClipboardClipboardSecurityPlatformSupported();

ClipboardSecurityStatus initializeClipboardSecurity() =>
    RustLib.instance.api.crateApiClipboardInitializeClipboardSecurity();

class ClipboardSecurityStatus {
  final bool supported;
  final bool ready;
  final String backend;
  final String? errorCode;

  const ClipboardSecurityStatus({
    required this.supported,
    required this.ready,
    required this.backend,
    this.errorCode,
  });

  @override
  int get hashCode =>
      supported.hashCode ^
      ready.hashCode ^
      backend.hashCode ^
      errorCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClipboardSecurityStatus &&
          runtimeType == other.runtimeType &&
          supported == other.supported &&
          ready == other.ready &&
          backend == other.backend &&
          errorCode == other.errorCode;
}
