// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clipboard_cipher`, `initialize`, `watch`

bool clipboardSecurityPlatformSupported() =>
    RustLib.instance.api.crateApiClipboardClipboardSecurityPlatformSupported();

ClipboardSecurityStatus initializeClipboardSecurity() =>
    RustLib.instance.api.crateApiClipboardInitializeClipboardSecurity();

ClipboardEncryptedData encryptClipboardText(
        {required String itemId, required String plaintext}) =>
    RustLib.instance.api.crateApiClipboardEncryptClipboardText(
        itemId: itemId, plaintext: plaintext);

String decryptClipboardText(
        {required String itemId,
        required List<int> nonce,
        required List<int> ciphertext}) =>
    RustLib.instance.api.crateApiClipboardDecryptClipboardText(
        itemId: itemId, nonce: nonce, ciphertext: ciphertext);

Stream<ClipboardCaptureEvent> watchClipboardText() =>
    RustLib.instance.api.crateApiClipboardWatchClipboardText();

class ClipboardCaptureEvent {
  final String? text;
  final String sourceApplication;
  final bool isHeartbeat;

  const ClipboardCaptureEvent({
    this.text,
    required this.sourceApplication,
    required this.isHeartbeat,
  });

  @override
  int get hashCode =>
      text.hashCode ^ sourceApplication.hashCode ^ isHeartbeat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClipboardCaptureEvent &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          sourceApplication == other.sourceApplication &&
          isHeartbeat == other.isHeartbeat;
}

class ClipboardEncryptedData {
  final Uint8List nonce;
  final Uint8List ciphertext;

  const ClipboardEncryptedData({
    required this.nonce,
    required this.ciphertext,
  });

  @override
  int get hashCode => nonce.hashCode ^ ciphertext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClipboardEncryptedData &&
          runtimeType == other.runtimeType &&
          nonce == other.nonce &&
          ciphertext == other.ciphertext;
}

class ClipboardSecurityStatus {
  final bool supported;
  final bool ready;
  final String backend;
  final String? errorCode;

  const ClipboardSecurityStatus({
    required this.supported,
    required this.ready,
    required this.backend,
    this.errorCode,
  });

  @override
  int get hashCode =>
      supported.hashCode ^
      ready.hashCode ^
      backend.hashCode ^
      errorCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClipboardSecurityStatus &&
          runtimeType == other.runtimeType &&
          supported == other.supported &&
          ready == other.ready &&
          backend == other.backend &&
          errorCode == other.errorCode;
}
