// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `configure`, `watch`

bool globalHotkeyPlatformSupported() =>
    RustLib.instance.api.crateApiHotkeyGlobalHotkeyPlatformSupported();

void configureGlobalHotkey({required String shortcut}) => RustLib.instance.api
    .crateApiHotkeyConfigureGlobalHotkey(shortcut: shortcut);

Stream<GlobalHotkeyEvent> watchGlobalHotkey() =>
    RustLib.instance.api.crateApiHotkeyWatchGlobalHotkey();

class GlobalHotkeyEvent {
  final bool activated;
  final bool registered;
  final String? errorCode;

  const GlobalHotkeyEvent({
    required this.activated,
    required this.registered,
    this.errorCode,
  });

  @override
  int get hashCode =>
      activated.hashCode ^ registered.hashCode ^ errorCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlobalHotkeyEvent &&
          runtimeType == other.runtimeType &&
          activated == other.activated &&
          registered == other.registered &&
          errorCode == other.errorCode;
}
