// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `current_session`, `execute`, `watch`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`

bool mediaPlatformSupported() =>
    RustLib.instance.api.crateApiMediaMediaPlatformSupported();

Future<MediaSession?> getCurrentMediaSession() =>
    RustLib.instance.api.crateApiMediaGetCurrentMediaSession();

Future<bool> mediaPlayPause() =>
    RustLib.instance.api.crateApiMediaMediaPlayPause();

Future<bool> mediaNext() => RustLib.instance.api.crateApiMediaMediaNext();

Future<bool> mediaPrevious() =>
    RustLib.instance.api.crateApiMediaMediaPrevious();

Future<bool> mediaSeek({required BigInt positionMs}) =>
    RustLib.instance.api.crateApiMediaMediaSeek(positionMs: positionMs);

Stream<MediaSession?> watchMediaSessions() =>
    RustLib.instance.api.crateApiMediaWatchMediaSessions();

class MediaCapabilities {
  final bool canPlay;
  final bool canPause;
  final bool canNext;
  final bool canPrevious;
  final bool canSeek;

  const MediaCapabilities({
    required this.canPlay,
    required this.canPause,
    required this.canNext,
    required this.canPrevious,
    required this.canSeek,
  });

  @override
  int get hashCode =>
      canPlay.hashCode ^
      canPause.hashCode ^
      canNext.hashCode ^
      canPrevious.hashCode ^
      canSeek.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaCapabilities &&
          runtimeType == other.runtimeType &&
          canPlay == other.canPlay &&
          canPause == other.canPause &&
          canNext == other.canNext &&
          canPrevious == other.canPrevious &&
          canSeek == other.canSeek;
}

enum MediaPlaybackState {
  closed,
  opened,
  changing,
  stopped,
  playing,
  paused,
  unknown,
  ;
}

class MediaSession {
  final String sourceAppId;
  final String sourceAppName;
  final String title;
  final String artist;
  final String albumTitle;
  final MediaPlaybackState playbackState;
  final BigInt positionMs;
  final BigInt durationMs;
  final Uint8List artwork;
  final String artworkContentType;
  final MediaCapabilities capabilities;

  const MediaSession({
    required this.sourceAppId,
    required this.sourceAppName,
    required this.title,
    required this.artist,
    required this.albumTitle,
    required this.playbackState,
    required this.positionMs,
    required this.durationMs,
    required this.artwork,
    required this.artworkContentType,
    required this.capabilities,
  });

  @override
  int get hashCode =>
      sourceAppId.hashCode ^
      sourceAppName.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      albumTitle.hashCode ^
      playbackState.hashCode ^
      positionMs.hashCode ^
      durationMs.hashCode ^
      artwork.hashCode ^
      artworkContentType.hashCode ^
      capabilities.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaSession &&
          runtimeType == other.runtimeType &&
          sourceAppId == other.sourceAppId &&
          sourceAppName == other.sourceAppName &&
          title == other.title &&
          artist == other.artist &&
          albumTitle == other.albumTitle &&
          playbackState == other.playbackState &&
          positionMs == other.positionMs &&
          durationMs == other.durationMs &&
          artwork == other.artwork &&
          artworkContentType == other.artworkContentType &&
          capabilities == other.capabilities;
}
