// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

MonitorResolution? resolveMonitor(
        {required MonitorMode mode,
        required List<String> displayIds,
        required String primaryId,
        String? activeId,
        String? fixedId}) =>
    RustLib.instance.api.crateApiMonitorResolveMonitor(
        mode: mode,
        displayIds: displayIds,
        primaryId: primaryId,
        activeId: activeId,
        fixedId: fixedId);

enum MonitorMode {
  primary,
  followActive,
  fixed,
  ;
}

class MonitorResolution {
  final String displayId;
  final bool usedFallback;

  const MonitorResolution({
    required this.displayId,
    required this.usedFallback,
  });

  @override
  int get hashCode => displayId.hashCode ^ usedFallback.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MonitorResolution &&
          runtimeType == other.runtimeType &&
          displayId == other.displayId &&
          usedFallback == other.usedFallback;
}
