// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

CoreStatus getCoreStatus() =>
    RustLib.instance.api.crateApiSystemGetCoreStatus();

class CoreStatus {
  final String name;
  final String version;
  final String targetOs;
  final String targetArch;

  const CoreStatus({
    required this.name,
    required this.version,
    required this.targetOs,
    required this.targetArch,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      version.hashCode ^
      targetOs.hashCode ^
      targetArch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreStatus &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          version == other.version &&
          targetOs == other.targetOs &&
          targetArch == other.targetArch;
}
