// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `current_state`, `set_awake`, `set_input_mute`, `set_output_mute`, `set_volume`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

bool systemControlsPlatformSupported() => RustLib.instance.api
    .crateApiSystemControlsSystemControlsPlatformSupported();

Future<SystemControlsState> getSystemControlsState() =>
    RustLib.instance.api.crateApiSystemControlsGetSystemControlsState();

Future<SystemControlsState> setOutputVolume({required int volumePercent}) =>
    RustLib.instance.api
        .crateApiSystemControlsSetOutputVolume(volumePercent: volumePercent);

Future<SystemControlsState> setOutputMuted({required bool muted}) =>
    RustLib.instance.api.crateApiSystemControlsSetOutputMuted(muted: muted);

Future<SystemControlsState> setInputMuted({required bool muted}) =>
    RustLib.instance.api.crateApiSystemControlsSetInputMuted(muted: muted);

Future<SystemControlsState> setKeepAwake({required bool active}) =>
    RustLib.instance.api.crateApiSystemControlsSetKeepAwake(active: active);

class AudioEndpointState {
  final bool available;
  final int volumePercent;
  final bool muted;

  const AudioEndpointState({
    required this.available,
    required this.volumePercent,
    required this.muted,
  });

  @override
  int get hashCode =>
      available.hashCode ^ volumePercent.hashCode ^ muted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioEndpointState &&
          runtimeType == other.runtimeType &&
          available == other.available &&
          volumePercent == other.volumePercent &&
          muted == other.muted;
}

class SystemControlsState {
  final AudioEndpointState output;
  final AudioEndpointState input;
  final bool keepAwake;

  const SystemControlsState({
    required this.output,
    required this.input,
    required this.keepAwake,
  });

  @override
  int get hashCode => output.hashCode ^ input.hashCode ^ keepAwake.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SystemControlsState &&
          runtimeType == other.runtimeType &&
          output == other.output &&
          input == other.input &&
          keepAwake == other.keepAwake;
}
